#include "zscript/decorations/barrels/ExplosiveBarrel.zsc"
#include "zscript/decorations/barrels/OilDrum.zsc"
#include "zscript/decorations/GlassTechPillars.zsc"

class Chair : Actor{
	default{
		+FloorClip;
		+Solid;
		Height 30;
		Radius 15;
	}
	States{
		Spawn:
		CHAI A -1;
		Stop;
	}
}

class RandomExperimentalWeapon : Health{
	default{
		Inventory.PickupMessage "Picked up an experimental weapon.\nYou cant use it because youre an imp.";
		Inventory.PickupSound "misc/w_pkup";
		Inventory.Amount 0;
		+INVENTORY.ALWAYSPICKUP;
	}
	states{
		Spawn:
			TNT1 A 0 A_Jump(255,"Sprite1","Sprite2","Sprite3","Sprite4","Sprite5","Sprite6");
			loop;
			
		Sprite1:
			DCAN A -1;
			stop;
			
		Sprite2:
			PLSP A -1;
			stop;
			
		Sprite3:
			KSWP A -1;
			stop;
			
		Sprite4:
			CHAN X -1;
			stop;
			
		Sprite5:
			LSCN E -1;
			stop;
			
		Sprite6:
			BFUG A -1;
			stop;
	}
}

//Por una cuestion de rendimiento, este es un tipo que desaparece a los 10 segundos.
//Lo tuve que escribir todo de vuelta porque UDB	 es un pelotudo.
class RandomExperimentalWeapon_Disappears : RandomExperimentalWeapon{
	states{
		Spawn:
			TNT1 A 0 A_Jump(255,"Sprite1","Sprite2","Sprite3","Sprite4","Sprite5","Sprite6");
			loop;
			
		Sprite1:
			DCAN A 525;
			TNT1 A 0 ResolveState("Null");
			
		Sprite2:
			PLSP A 525;
			TNT1 A 0 ResolveState("Null");
			
		Sprite3:
			KSWP A 525;
			TNT1 A 0 ResolveState("Null");
			
		Sprite4:
			CHAN X 525;
			TNT1 A 0 ResolveState("Null");
			
		Sprite5:
			LSCN E 525;
			TNT1 A 0 ResolveState("Null");
			
		Sprite6:
			BFUG A 525;
			TNT1 A 0 ResolveState("Null");
	}
}

Class BrokenLamp : Actor{
	default{
		+FloorClip;
		+Solid;
		Height 30;
		Radius 10;
	}
	States{
		Spawn:
		BLMP A -1;
		Stop;
	}
}

//////////////////////////////////UAC HOLOGRAMS////////////////////////////////////
Class UACHolo1 : Actor{
	default{
		Scale 0.5;
		Renderstyle "Add";
		+NOGRAVITY;
	}
	States{
		Spawn:
			UAC1 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
		Loop;
	}
}

Class UACHolo2 : UACHolo1{
	States{
		Spawn:
			UAC1 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Cyan Holograms
Class UACHolo3 : UACHolo1{
	States{
		Spawn:
			UAC2 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner2", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
Class UACHolo4 : UACHolo1{
	States{
		Spawn:
			UAC2 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner2", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Orange Holograms
Class UACHolo5 : UACHolo1{
	States{
		Spawn:
			UAC3 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner3", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}

Class UACHolo6 : UACHolo1{
	States{
		Spawn:
			UAC3 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner3", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Plasma Particle Spawner
Class PlasmaSpawner : Actor{
	default{
		Alpha 0.75;
		RenderStyle "Add";
		+NOGRAVITY;
		+DONTSPLASH;
		+NOCLIP;
		-SOLID;
		Projectile;
	}
	States{
		Spawn:
			PLEM AAAAAAAAAAAAAAAA 1 BRIGHT A_FadeOut(0.09);
			stop;
		Death:
			TNT1 A 1;
			stop;
	}
}
Class PlasmaSpawner2 : plasmaspawner{
	States{
		Spawn:
			PLEM BBBBBBBBBBBBBBBB 1 BRIGHT A_FadeOut(0.09);
			stop;
		Death:
			TNT1 A 1;
			stop;
	}
}
Class PlasmaSpawner3 : plasmaspawner{
	States{
		Spawn:
			PLEM CCCCCCCCCCCCCCCC 1 BRIGHT A_FadeOut(0.09);
			stop;
		Death:
			TNT1 A 1;
			stop;
	}
}


Class PlasmaSpawnerGreen : Actor{
	default{
		Scale 0.5;
		Renderstyle "Add";
		+NOGRAVITY;
	}
	States{
		Spawn:
			TNT1 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}

///////////////////////////////////PIPES/////////////////////////////////////////
Class HPipe1 : Actor{
	default{
		Radius 16;
		Height 128;
		Tag "Pipe 1";
		+SOLID;
	}
	States{
		Spawn:
			PIP1 A -1;
			Stop;
	}
}

Class HPipe2 : Actor{
	default{
		Radius 16;
		Height 128;
		Tag "Pipe 2";
		+SOLID;
	}
	States{
		Spawn:
			PIP2 A -1;
			Stop;
	}
}

Class HPipe3 : Actor{
	default{
		Radius 16;
		Height 128;
		Tag "Pipe 3";
		+SOLID;
	}
	States{
		Spawn:
			PIP3 A -1;
			Stop;
	}
}

Class HPipe4 : Actor{
	default{
		Radius 16;
		Height 128;
		Tag "Pipe 4";
		+SOLID;
	}
	States{
		Spawn:
			PIP4 A -1;
			Stop;
	}
}

Class HPipe5 : Actor{
	default{
		Radius 16;
		Height 128;
		Tag "Pipe 5";
		+SOLID;
	}
	States{
		Spawn:
			PIP5 A -1;
			Stop;
	}
}


///////////////////////////GLASS TECH PILLARS///////////////////////////////////

//STANDARD BREAKABLE



//////////////////////////// AnimatedUACLogo ////////////////////////////

//DECAL ANIMATOR
class RedUACPainter : Actor{
	int Offseted;
	default{
		Radius 2;
		Height 2;
		+NOINTERACTION;
		+NOGRAVITY;
	}
	States{
		Spawn:
		TNT1 A 0;
		//fall through
		Paint:
		TNT1 A 16 A_SpawnItemEx ("RedUPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
		TNT1 A 16 A_SpawnItemEx ("RedAPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
		TNT1 A 16 A_SpawnItemEx ("RedCPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
		TNT1 A 32;
		loop;
	}
}

class GreenUACPainter : RedUACPainter{
  States{
  Spawn:
	TNT1 A 0;
	//fall through
  Paint:
    TNT1 A 16 A_SpawnItemEx ("GreenUPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("GreenAPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("GreenCPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 32;
    loop;
  }
}

class BlueUACPainter : RedUACPainter{
  States{
  Spawn:
	TNT1 A 0;
	//fall through
  Paint:
    TNT1 A 16 A_SpawnItemEx ("BlueUPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("BlueAPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("BlueCPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 32;
    loop;
  }
}

class YellowUACPainter : RedUACPainter{
  States{
  Spawn:
	TNT1 A 0;
	//fall through
  Paint:
    TNT1 A 16 A_SpawnItemEx ("YellowUPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("YellowAPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 16 A_SpawnItemEx ("YellowCPainter", 0, 0, 0, 100, 0, 0, 0, 0, 0);
    TNT1 A 32;
    loop;
  }
}
