class Cientist1 : Actor{
	default{
		speed 2;
		+SOLID;
		radius 32;
		height 64;
	}
	states{
		Spawn:
			CNT1 AABBCCDD 2 A_Wander;
			loop;
	}
}

class Cientist1_Patrol : Cientist1{
	default{
		speed 8;
		//MONSTER;
	}
	states{
		Spawn:
			CNT1 AABBCCDD 4 A_Look;
			loop;
		See:
			CNT1 AABBCCDD 4 A_Chase;
			loop;
	}
}

class Cientist2 : Actor{
	default{
		speed 0;
		+SOLID;
		radius 32;
		height 64;
	}
	states{
		Spawn:
			CNT2 A -1;
			stop;
	}
}