class ExplosiveBarrelWeapon : DoomWeapon{
	default{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 0;
		Weapon.AmmoGive 0;
		Weapon.AmmoType "Cell";
		Weapon.YAdjust 48;
		+WEAPON.NOAUTOFIRE;
	}
	states{
		Ready:
			BEXW ABCDCB 1 A_WeaponReady;
			Loop;
		Deselect:
			BEXW A 1 A_Lower;
			Loop;
		Select:
			BEXW A 1 A_Raise;
			Loop;
		Fire:
			BEXW A 1 {
			Actor pPlayer = GetPointer(AAPTR_PLAYER1);
			
			A_FireProjectile("ExplosiveBarrelProjectile");
			
			if (pPlayer is "ImpPlayer" || pPlayer is "FlyingImpPlayer")
				A_GiveInventory("ImpArm",1,AAPTR_PLAYER1);
				
			if (pPlayer is "DarkImpPlayer")
				A_GiveInventory("DarkImpArm",1,AAPTR_PLAYER1);
				
			A_TakeInventory("ExplosiveBarrelWeapon",1,0,AAPTR_PLAYER1);
			}
			TNT1 A 0;
		Spawn:
			BEXW A -1;
			Stop;
	}
}